name: Depoly2 To EC2

on: 
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-lastes
        steps:
            - name: Github Repository에 올린 파일 불러오기
              # github 파일 불러오는 라이브러리
              uses: actions/checkout@v4
            
            - name: JDK 17버전 설치
              # JDK 다운 받는 라이브러리
              uses: actions/setup-java@v4
              with: 
                distribution: tenurin
                java-version: 17
            
            - name: application.yml 파일 만들기
              # github actions에서 Application.yml 파일을 만듦
              run : echo "${{ secrets.APPLICATION_PROPERTIES}}" > ./src/main/resources/application.yml

            - name: 테스트 및 빌드하기
              run : ./gradlew clean build
